### ISSUE TITLE
Visdom JSON error

### ISSUE THREAD

**Issue by michaelklachko** [human-analysis/pytorchnet#4]
I'm getting the following error when trying to run python main.py  (using pytorch 4.1 and visdom 0.1.8.5): 

```
Traceback (most recent call last):
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/site-packages/visdom/__init__.py", line 446, in _send
    data=json.dumps(msg),
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Scatter' is not JSON serializable
```

**Comment by vboddeti** [comment]
Thanks for pointing this out, it has now been fixed.

**Comment by natolambert** [comment]
Hey - I'm still receiving this error? Is it resolved in current release?

`Traceback (most recent call last):
  File "/private/home/nol/.conda/envs/pets/lib/python3.6/site-packages/visdom/__init__.py", line 446, in _send
    data=json.dumps(msg),
  File "/private/home/nol/.conda/envs/pets/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/private/home/nol/.conda/envs/pets/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/private/home/nol/.conda/envs/pets/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/private/home/nol/.conda/envs/pets/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Scatter' is not JSON serializable`
pytorch 1.1, visdom 0.1.8.5... For more info, I am trying to run 

'vis._send({'data': [trace], 'layout': layout, 'win': 'mywin'})'

**Comment by vboddeti** [comment]
That error has been fixed in September 2018. If you are still seeing that error with the current version let me know, I am not seeing such errors on my end.

**Comment by shalini-maiti** [comment]
Hello, I'm receiving this error when I try to call -
fig = px.scatter_3d()
fig1 = px.scatter_3d()
fig2 = px.line_3d()
fig = go.Figure(data=fig.data + fig1.data + fig2.data)
fig.update_layout(title=title)
image = 
'vis._send({'data': [trace], 'layout': layout, 'win': 'mywin'})'

visdom version 0.1.8.9

Is this fixed somewhere? Or am I making a mistake?
