### ISSUE TITLE
Imagenet training

### ISSUE THREAD

**Issue by michaelklachko** [human-analysis/pytorchnet#5]
What is the expected structure of ImageNet dataset? I'm trying to pass train folder with folder per class train jpg images, and val folder with all 50k validation images. But it's not clear how to pass labels for val examples using datasets.ImageFolder in dataloader.py.

**Comment by michaelklachko** [comment]
Ok, so it seems like it expects val images to be in folders per class, as explained here: https://github.com/pytorch/examples/tree/master/imagenet

Yet I still get the following "Assertion `t >= 0 && t < n_classes` failed" error: 
```
/opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 51, in main
    loss_train = trainer.train(epoch, loaders)
  File "/home/michael/pytorchnet/train.py", line 138, in train
    loss.backward()
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/michael/miniconda2/envs/pt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/THC/generic/THCTensorMath.cu:26
NoneType: None
```

I can run https://github.com/pytorch/examples/blob/master/imagenet/main.py just fine, so must be something missing in your code...

**Comment by michaelklachko** [comment]
Oh, I forgot to change number of classes in args file, my bad!
